[package]
name = "mikado"
version = "0.2.3"
authors = ["Adam Thibert <adamthibert01@gmail.com>"]
edition = "2024"
license = "MIT"
readme = "README.md"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[build-dependencies]
vergen-gitcl = { version = "10", features = ["build"] }

[dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_SystemServices"] }
crochet = "0.2"
log = "0.4"
env_logger = "0.11"
anstyle = "1"
anstream = "1"
panic-log = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
confy = "2"
anyhow = "1"
ureq = { version = "3.4", features = ["json"] }
url = "2.3"
either = { version = "1", features = ["serde"] }
num_enum = "0.7"
chrono = "0.4"
kbinxml = { git = "https://github.com/mbilker/kbinxml-rs.git", version = "3.1.0" }
bytes = "1.4"
dynfmt = { version = "0.2", default-features = false, features = ["curly"] }
